### ISSUE TITLE
Multiple install script runs seem to keep adding the same line to bashrc

### ISSUE THREAD

**Issue by aplowman** [hpcflow/install-scripts#59]
On the CSF, I seem to have ended up with multiple `export PATH`s in my ~/.bashrc:

![image](https://github.com/hpcflow/install-scripts/assets/5176471/c97f0bcf-4e95-40e1-b900-6462d817208b)

**Comment by cjfullerton** [comment]
There is a check in the install script for the links folder being on the path that means this shouldn't happen. Perhaps it's not working.

**Comment by cjfullerton** [comment]
I've tried to replicate this on my laptop:

I found that it happens if I run the install script twice to install two versions of hpcflow in the same terminal session. This means .bashrc/.zshrc aren't reloaded so the hpcflow folder doesn't appear in the path so the line gets added twice.

Installing a version, reloading the terminal and installing another version leaves us with just one entry in .bashrc/.zshrc since the dotfiles get reloaded when the terminal is restarted.

I'll check what happens on CSF when I'm on campus tomorrow, but suspect I'll find the same thing.

**Comment by aplowman** [comment]
That makes sense. Maybe we should check if the specific line to be added already exists in the file, before adding it, if we find it is not on PATH already?

**Comment by cjfullerton** [comment]
I agree, should be doable with grep.

**Comment by gcapes** [comment]
I think I can see a mistake [here ](https://github.com/hpcflow/install-scripts/blob/main/src/install-hpcflow.sh#L271)

It needs a `*` after the case value so that it matches the value at any point in the PATH, not just when it occurs at the end.
```
        *:"${folder}"/links:*) onpath=true ;;
```

This doesn't negate the problem when doing multiple installs in the same terminal session. I'm working on PR for that too.
